### PR TITLE
Imu preprocessing gyro

### PR DESCRIPTION
**Pull request by nienketimmermans**
Hee Erik, ik heb een aparte functie aangemaakt om alleen de gyroscope data te preprocessen. Dat vond ik voor nu het makkelijkst. Evt kan het later met de preprocess_imu_data functie gecombineerd worden.

### CODE REVIEW

**Comment by Erikpostt** [comment]
@nienketimmermans this is currently on your plate, correct?

**Comment by nienketimmermans** [comment]
Ja ga er vandaag mee verder!

**Comment by nienketimmermans** [comment]
Hi, I modified the IMU preprocessing function that now takes the sensor type into account. I also took the multiplication with scaling factors out of the resample function. @Erikpostt the preprocessed IMU data seems to be changed too, but I checked with the previous version and it is the same.

**Review by Erikpostt — APPROVED** [review]
Looking good from my perspective. I committed some changes related to docstrings, variable names and the order of the processing steps. @KarsVeldkamp on to you.

**Review by KarsVeldkamp — APPROVED** [review]
Ziet er goed uit! Wmb ready for merge

**Review by Erikpostt — APPROVED** [review]
Conflicts during merge were resolved well, ready to merge.

**Pull request merged**
