### PR TITLE
Extracting features gait

### PR DESCRIPTION
**Pull request by Erikpostt**
PR contains

- Updates on `imu_preprocessing.py` with added functionality for windowing and feature engineering;
- Directory of .ipynb files for documentation purposes

Waiting with reviewing (and merging) until

- Currently waiting for merging of PR #2 to resolve changes in `imu_preprocessing.py`;
- Notebooks are still missing expected output

### CODE REVIEW

**Comment by vedran-kasalica** [comment]
I recommend merging the `main` branch into this branch after PR #6 receives approval. This step will ensure accurate testing of the changes.

**Comment by Erikpostt** [comment]
@vedran-kasalica what do you recommend here now?

**Comment by vedran-kasalica** [comment]
> I recommend merging the `main` branch into this branch after PR #6 receives approval. This step will ensure accurate testing of the changes.

@Erikpostt  I would recommend this, but we can also do that together on Thursday.

**Comment by Erikpostt** [comment]
@vedran-kasalica what do you think of the proposed changes?

**Comment by vedran-kasalica** [comment]
> @vedran-kasalica what do you think of the proposed changes?

The changes look good! 
I tested it locally and it all runs well (although I do generate binaries that are different on the byte level). We should probably save the outputs of the Notebooks in a separate folder (and add it to .gitignore so we don't track them) to be able to compare the results to the expected values. When I run it now I override the test data used for comparison. 

I will finish reviewing the code tomorrow. We will probably merge the PR and then set up some tests based on your Notebooks and start adding more modules to the toolbox. I have some suggestions (e.g., we probably don't need to store the field `meta_filename` in our `_meta.json` files), but I will make a separate PR for that later, so we can distinguish refactoring from this PR.

**Comment by vedran-kasalica** [comment]
@Erikpostt it was not clear to me what is the content of `rotation_meta` file. We don't have an intermediary file specified in the [pipeline](https://raw.githubusercontent.com/biomarkersParkinson/docs/main/architecture/pipeline-architecture.drawio.png?token=GHSAT0AAAAAACNVSYKOUN3NIBLWUTK6E6P2ZPGD7QA) under that name, right?

**Comment by Erikpostt** [comment]
> @Erikpostt it was not clear to me what is the content of `rotation_meta` file. We don't have an intermediary file specified in the [pipeline](https://raw.githubusercontent.com/biomarkersParkinson/docs/main/architecture/pipeline-architecture.drawio.png?token=GHSAT0AAAAAACNVSYKOUN3NIBLWUTK6E6P2ZPGD7QA) under that name, right?

You are right Vedran, this is the `gyro pre-processed` (grey) block at the _2.preprocessed_data_ level. As to your comment, it would probably be a good idea to be consistent in the naming of the files.

**Review by vedran-kasalica — APPROVED** [review]
The changes look good. I tested the Notebooks locally and they run without issues. 

Instead of requesting changes to the PR, I opened an issue (see #8). It would be good to address it soon after merging this PR. 

I propose to merge the PR and create new PRs to address the follow-up refactoring. 

@kretep once you review the PR, feel free to merge it.

**Review by kretep — APPROVED** [review]

**Pull request merged**
